# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
    backend "azurerm" {
        resource_group_name  = "terraform-shared"
        storage_account_name = "devsomethingunique"
        container_name = "dev-tfstate"
        key = "common-my-first-resource-group.tfstate"
    }
}
