# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
    required_version = ">= 1.9.6"
    required_providers {
        azurerm = {
            source = "hashicorp/azurerm"
            version = ">= 4.3.0, <= 4.3.0"
        }
    }
}

provider "azurerm" {
    subscription_id = "1234567-1234-1234-1234-12345678901"
    features {
        key_vault {
            purge_soft_delete_on_destroy = true
            recover_soft_deleted_key_vaults = true
        }
    }
}
